title: Captain's Blog
author: deadstocky
email: donovanhong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a sample blog that was made while learning Github's Learning
  Lab. I'm not sure if I'll actually be updating this blog, but stay
  tuned just in case.

# social links
instagram_username: deadstocky
github_username:  deadstocky

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
